Panel:
  server_name: Lobby
  console_name: System
  port: 5888
  java_api_key: test
  log_to_console: true
  
ConsolePlayers:
  - NaysKutzu
LockedConsoleCommands:
  - plugman
  - stop
  - restart
Messages:
  # Prefix
  Prefix: "YourServer &7> "
  NoPermission: "You do not have any permissions to run this command!"
  OnlyForPlayers: "This command is only for ingame players!"
  # Console
  ConsoleSyntax: "Use: /console [Command]"
  LockedCommand: "This command is blocked!"
  Complete: "The command has been executed in the server console!!"
  # Join Messages
  JoinMessage: "%player% has joined the server!"
  LeaveMessage: "%player% has left the server!"
  # AntiUserSteal
  AntiUserSteal: "Why you trying to steal an user account?"
  # AntiSyntax
  AntiSyntax: "Sorry, but you can't use direct plugin syntax on the server"
  # AntiCheat
  KickFly: "[MythicalAC] You are not allowed to fly!"
  # ClearChat
  ClearChat: "Chat has been cleared by %mcpanelx_user%!"
  # Death Messages
  DeathMessage: "%player% has died!"
  # ChatLock
  ChatLocked: "Chat has been %mcpanelx_status% by %mcpanelx_user%!"
  ChatLockedPlayer: "Chat has been locked by an administrator!"
  ChatLockedStatusLocked: 'Locked'
  ChatLockedStatusUnLocked: 'Unlocked'
  
AntiCheat:
  # Should we enable the AntiCheat system?
  enabled: true

# Should we let users form the ConsolePlayers use their console?
InGameConsole:
  enabled: true

AntiDisconnectSpam:
  # Should we enable the AntiDisconnectSpam system?
  enabled: true
  # How many times can a player disconnect in a certain time?
  limit: 3
  # How many seconds should we check for disconnects?
  time: 10

# Should we enable the Discord webhook system?
Discord:
  enabled: true
  webhook: ""

# Should we enable the AntiUserSteal system?
AntiUserSteal:
  enabled: true
# Should we disable /<pluginname>:<command> from the server?
AntiSyntax:
  enabled: true

# Should we display custom join/death messages?
CustomMessages:
  enabled: true

# Should we enable command blockers for console/remote connections?
CommandBlocker:
  enabled: true
# Should we enable saving the messages/commands in the database?
Database:
  enabled: true
  host: 127.0.0.1
  port: 3306
  username: "root"
  password: ""
  database: "mcpanelx"

ChatFormatter:
  enabled: true
  # Placeholders:
  # {message} - the chat message
  # {name} - the player's name
  # {displayname} - the player's display name / nickname
  # {world} - the world name of the player's current world
  # {prefix} - the player's highest priority prefix
  # {suffix} - the player's highest priority suffix
  # {prefixes} - the player's prefixes sorted by the highest priority
  # {suffixes} - the player's suffixes sorted by the highest priority
  # {username-color} - the player's or the group's username color
  # {message-color} - the player's or the group's message color
  #
  # To reload the configuration restart your server!
  chat-format: "{prefix}{name}&r: {message}"

  group-formats:
  #  default: "[default] {name}&r: {message}"
  #  admin: "[admin] {name}&r: {message}"